### ISSUE TITLE
Çeviri ekibi kurulabilir mi?

### ISSUE THREAD

**Issue by sametcodes** [gelis-tr-io/destek#1]
Bir süredir farklı farklı açık kaynak projelerin çevirileri üzerine uğraşıyorum. Bazı projeler geniş kapsamlı olduğundan ve teknik çeviriler gerektiğinden yarım kalabiliyor. Örneğin daha önce [Seeing-Theory](https://github.com/selmansamet/Seeing-Theory)'nin çevirisinin yarısından fazlasını tamamlamış ama teknik bilgi yetersizliğinden dolayı yarım bırakmak zorunda kalmıştım.

Topluluk içinde bir çeviri ekibi kurulursa, çeviriler organize bir şekilde daha hızlı tamamlanabilir. Böyle bir ekibin, en azından bir çekirdek ekibin kurulması için nasıl hareket etmeliyiz?

**Comment by hurata** [comment]
Olabilir  aslında Crowdin tarzı bir servis kullanılabilir .
Crowdin = "Servisleri, websiteleri yerel dillere çevirmek için kullanılan bir servis."
Websitesinde de github için plugini olduğu yazıyor. 
https://crowdin.com

Saygılarımla

**Comment by tarikguney** [comment]
Yapilan cevirilere insanlarin ulasmasi ve yeni cevirilerin eklenmesi icin oncelikle bir tane repo eklenebilir.

**Comment by tarikguney** [comment]
Cevilirler icin yeni repo olusturuldu. https://github.com/gelis-tr-io/ceviriler Ceviri yapmak isteyenler burada yeni klasor olusturmak sureti ile insanlari yaptiklari cevirilere katki saglamaya cagirabilirler. Tamamlanmis ceviriler, `readme.md` dosyasinda herkesin gorebilecegi bir sekilde sergilenebilir.

**Comment by sametcodes** [comment]
Birden fazla dosya içeren çevirilerde, örneğin çok sayfalı bir döküman için, tek bir repo üzerinde çalışmak, diğer değişiklik yapılan çeviri projeleriyle çakışmalara sebep olabilir. Bu şekilde kapsamlı çeviri projeleri için yeni repolar açmak mı uygundur, yoksa farklı bir çözüm üretilebilir mi?
